# Header
menu:
  #Home: /
  #Archives: /archives
  home: / || home
  worksite: /worksite/ || laptop
  designsite: /designsite/ || desktop
  learnsite: /learnsite/ || book
  gamesite: /gamesite/ || gamepad
  videosite: /videosite/ || video
  statistical: /statistical/ || video
  categories: /categories/ || th
  #archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  tags: /tags/ || tags
  about: /about/ || user
  #commonweal: /404/ || heartbeat
#rss: /atom.xml

# Enable/Disable menu icons.
menu_icons:
  enable: true
  
  home: home
  worksite: laptop
  designsite: desktop
  learnsite: book
  gamesite: gamepad
  videosite: youtube
  statistical: video
  about: user
  categories: th
  tags: tags
  archives: archive
  commonweal: heartbeat


# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
