
# Header
menu:
  #Home: /
  #Archives: /archives
  #home: /
  categories: /categories/
  worksite: /worksite/
  designsite: /designsite/
  learnsite: /learnsite/
  #gamesite: /gamesite/
  #videosite: /videosite/
  statistical: /statistical/
  archives: /archives/
  #schedule: /schedule/
  #sitemap: /sitemap.xml
  #tags: /tags/ 
  #about: /about/
  #commonweal: /404/ 
#rss: /atom.xml

# Enable/Disable menu icons.
menu_icons:
  enable: true
  
  #home: home
  worksite: laptop
  designsite: desktop
  learnsite: book-open
  gamesite: gamepad
  videosite: video
  statistical: chart-pie
  about: user
  categories: th
  tags: tags
  archives: archive
  commonweal: heartbeat

# Custom Logo.
# !!Only available for Default Scheme currently.
# Options:
#   enabled: [true/false] - Replace with specific image
#   image: url-of-image   - Images's url
custom_logo:
  enabled: true
  image: home

# _custom Carousel component data
#
# Options:
#   enabled: [true/false] - Replace with specific image
#   title: Carousel title<标题>
#   descropt: Carousel descropt<描述>
#   image: url-of-image   - Images's url
#
Carousel_Work:
  enabled: true
  title: 工作站
  linktitle: 查看全部作品
  descropt: 作品摘要
  CarouselImgs:
    image1: /css/images/carousel/sub-bg-8.jpg
    image2: /css/images/carousel/sub-bg-2.jpg
    image3: /css/images/carousel/sub-bg-3.jpg
    image4: /css/images/carousel/sub-bg-4.jpg
    image5: /css/images/carousel/sub-bg-7.jpg
    image6: /css/images/carousel/sub-bg-8.jpg
    image7: /css/images/carousel/sub-bg-2.jpg
    image8: /css/images/carousel/sub-bg-3.jpg
    image9: /css/images/carousel/sub-bg-4.jpg
    image10: /css/images/carousel/sub-bg-7.jpg
    image11: /css/images/carousel/sub-bg-5.jpg
    image12: /css/images/carousel/sub-bg-8.jpg
    image13: /css/images/carousel/sub-bg-2.jpg
    image14: /css/images/carousel/sub-bg-3.jpg
    image15: /css/images/carousel/sub-bg-6.jpg

Carousel_Design:
  enabled: true
  title: 设计站
  linktitle: 查看全部内容
  descropt: 内容摘要
  CarouselImgs:
    image1: /css/images/carousel/sub-bg-8.jpg
    image2: /css/images/carousel/sub-bg-2.jpg
    image3: /css/images/carousel/sub-bg-3.jpg
    image4: /css/images/carousel/sub-bg-4.jpg
    image5: /css/images/carousel/sub-bg-7.jpg
    image6: /css/images/carousel/sub-bg-8.jpg
    image7: /css/images/carousel/sub-bg-2.jpg
    image8: /css/images/carousel/sub-bg-3.jpg
    image9: /css/images/carousel/sub-bg-4.jpg
    image10: /css/images/carousel/sub-bg-7.jpg
    image11: /css/images/carousel/sub-bg-5.jpg
    image12: /css/images/carousel/sub-bg-8.jpg
    image13: /css/images/carousel/sub-bg-2.jpg
    image14: /css/images/carousel/sub-bg-3.jpg
    image15: /css/images/carousel/sub-bg-6.jpg

Carousel_Learn:
  enabled: true
  title: 学习站
  linktitle: 查看全部记录
  descropt: 记录摘要
  CarouselImgs:
    image1: /css/images/carousel/sub-bg-8.jpg
    image2: /css/images/carousel/sub-bg-2.jpg
    image3: /css/images/carousel/sub-bg-3.jpg
    image4: /css/images/carousel/sub-bg-4.jpg
    image5: /css/images/carousel/sub-bg-7.jpg
    image6: /css/images/carousel/sub-bg-8.jpg
    image7: /css/images/carousel/sub-bg-2.jpg
    image8: /css/images/carousel/sub-bg-3.jpg
    image9: /css/images/carousel/sub-bg-4.jpg
    image10: /css/images/carousel/sub-bg-7.jpg
    image11: /css/images/carousel/sub-bg-5.jpg
    image12: /css/images/carousel/sub-bg-8.jpg
    image13: /css/images/carousel/sub-bg-2.jpg
    image14: /css/images/carousel/sub-bg-3.jpg
    image15: /css/images/carousel/sub-bg-6.jpg


Carousel_Game:
  enabled: true
  title: 游戏站
  linktitle: 查看全部游戏
  descropt: 游戏摘要
  CarouselImgs:
    image1: /css/images/carousel/sub-bg-8.jpg
    image2: /css/images/carousel/sub-bg-2.jpg
    image3: /css/images/carousel/sub-bg-3.jpg
    image4: /css/images/carousel/sub-bg-4.jpg
    image5: /css/images/carousel/sub-bg-7.jpg
    image6: /css/images/carousel/sub-bg-8.jpg
    image7: /css/images/carousel/sub-bg-2.jpg
    image8: /css/images/carousel/sub-bg-3.jpg
    image9: /css/images/carousel/sub-bg-4.jpg
    image10: /css/images/carousel/sub-bg-7.jpg
    image11: /css/images/carousel/sub-bg-5.jpg
    image12: /css/images/carousel/sub-bg-8.jpg
    image13: /css/images/carousel/sub-bg-2.jpg
    image14: /css/images/carousel/sub-bg-3.jpg
    image15: /css/images/carousel/sub-bg-6.jpg

Carousel_Video:
  enabled: true
  title: 视频站
  linktitle: 查看全部视频
  descropt: 视频摘要
  CarouselImgs:
    image1: /css/images/carousel/sub-bg-8.jpg
    image2: /css/images/carousel/sub-bg-2.jpg
    image3: /css/images/carousel/sub-bg-3.jpg
    image4: /css/images/carousel/sub-bg-4.jpg
    image5: /css/images/carousel/sub-bg-7.jpg
    image6: /css/images/carousel/sub-bg-8.jpg
    image7: /css/images/carousel/sub-bg-2.jpg
    image8: /css/images/carousel/sub-bg-3.jpg
    image9: /css/images/carousel/sub-bg-4.jpg
    image10: /css/images/carousel/sub-bg-7.jpg
    image11: /css/images/carousel/sub-bg-5.jpg
    image12: /css/images/carousel/sub-bg-8.jpg
    image13: /css/images/carousel/sub-bg-2.jpg
    image14: /css/images/carousel/sub-bg-3.jpg
    image15: /css/images/carousel/sub-bg-6.jpg



# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
